# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dialog_fill_xlsx.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_fill_xlsx(object):
    def setupUi(self, dialog_fill_xlsx):
        dialog_fill_xlsx.setObjectName("dialog_fill_xlsx")
        dialog_fill_xlsx.resize(354, 213)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_fill_xlsx)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.www = QtWidgets.QWidget(dialog_fill_xlsx)
        self.www.setObjectName("www")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.www)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_fp = QtWidgets.QLineEdit(self.www)
        self.edit_fp.setObjectName("edit_fp")
        self.horizontalLayout.addWidget(self.edit_fp)
        self.btn_select_fp = QtWidgets.QPushButton(self.www)
        self.btn_select_fp.setObjectName("btn_select_fp")
        self.horizontalLayout.addWidget(self.btn_select_fp)
        self.horizontalLayout_2.addWidget(self.www)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(dialog_fill_xlsx)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_3.addWidget(self.btn_start)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(dialog_fill_xlsx)
        QtCore.QMetaObject.connectSlotsByName(dialog_fill_xlsx)

    def retranslateUi(self, dialog_fill_xlsx):
        _translate = QtCore.QCoreApplication.translate
        dialog_fill_xlsx.setWindowTitle(_translate("dialog_fill_xlsx", "Dialog"))
        self.btn_select_fp.setText(_translate("dialog_fill_xlsx", "选择Excel"))
        self.btn_start.setText(_translate("dialog_fill_xlsx", "开始转换"))
